### PR TITLE
feat: blog share update part 1

### PR DESCRIPTION
**Pull request by georgiee**
This is a variant of  #307, let's see if we can get this running. I removed the refactoring of the preview image generation.

+ Blog Images instead of cards
+ SEO component update to always except paths
+ Correct branch url generation

Preview:
https://satellytescommain21751-gkfixblogsharing2.gtsb.io/

Sharing works:
Screen Shot 2021-12-22 at 16 48 03
Screen Shot 2021-12-22 at 16 47 49

### CODE REVIEW

**Comment by georgiee** [comment]
Force pushed to force a rebuild (incremental check)

**Comment by georgiee** [comment]
~on auto merge if anyone reviews as I have to leave and I would like to see this merged if good 🤓~
this can wait.

**Review by feedm3 — APPROVED** [review]
Smoke test was successful, also no issues were found in the code. Good to go 👍

**Comment by georgiee** [comment]
thanks 🙏

**Pull request merged**
