### PR TITLE
chore: adjust blog font sizes

### PR DESCRIPTION
**Pull request by milljoniaer**
This PR adjusts the font sizes mainly on Blog posts in the following way:

- IntroText desktop: 20 -> 22px
- ArtilceText/Text in general desktop: 16 -> 18px
- SmallTitle 20 -> 22px
- Code Text: same size like normal text

Please also check the other Pages if some fonts look weird. But it should n't be that way

### CODE REVIEW

**Review by hofmann-felix — COMMENTED** [review]
I noticed that some of the changes do not match [Figma](https://www.figma.com/file/FWlI63N28LP7BxqNqj1bGw/sy-004-(Design!)?node-id=3705%3A29456) (e.g. HeadlineS, ArticleText on mobile, IntroText on mobile). Since I don't know where the requirements for this PR come from I can't tell if the text styles are correct.

**Comment by milljoniaer** [comment]
Eric asked directly if we could change the font sizes slightly. I am in contact with him about the design questions. Until I get his okay, I will convert the PR to a draft. Thank you for your comment, I will then ask for a technical review.

**Comment by milljoniaer** [comment]
I justed got the okay by the design crew, feel free to give a review on this PR.

**Review by feedm3 — APPROVED** [review]

**Review by fischeversenker — APPROVED** [review]
I didn't compare with Figma, but can confirm that everything (still) looks lovely 👍

**Pull request merged**
