### PR TITLE
chore: update translation format

### PR DESCRIPTION
**Pull request by georgiee**
1. I flatted the hierarchy of our translation files and imported them into our poeditor.com account.
2. Updated missing translations
3. Invited everyone from @satellytes/website-crew to poeditor either as contributor or admin

### CODE REVIEW

**Comment by ghost** [comment]
# [Gatsby Cloud](https://www.gatsbyjs.com) Build Report
**satellytes.com-main**

:tada: Your build was successful! [See the Deploy preview here.](https://satellytescommain21751-gktranslationchange.gtsb.io)

## Build Details

[View the build logs here.](https://gatsbyjs.com/dashboard/f215130d-15e3-4176-9252-e13166fe48de/sites/674be368-adf0-4ac5-8fae-f9a4493adc51/builds/1687b56e-6f75-4bcc-a5c6-4bfb820e2386/details)

:clock1: Build time: **1m**

## Performance

### Lighthouse report

| Metric | Score |
| ----- | ---- |
| Performance |   :large_orange_diamond: 73   |
| Accessibility |   :green_heart: 92   |
| Best Practices |   :green_heart: 100   |
| SEO |   :large_orange_diamond: 71   |

:link: [View full report](https://build-1687b56e-6f75-4bcc-a5c6-4bfb820e2386.gtsb.io/reports/lighthouse/index.html)

**Review by hofmann-felix — APPROVED** [review]
Thanks for the invitation to poeditor.com 👍 I created an account for me 

I quickly checked all the sites and it seems to be working. What exactly are the advantages of that flat hierarchy? I was always told in other PRs to avoid it.

**Comment by georgiee** [comment]
> I quickly checked all the sites and it seems to be working. What exactly are the advantages of that flat hierarchy? I was always told in other PRs to avoid it.

I don't know when we decided for the nested approach but I have never worked with nested files for some simple reasons: findability, cognitive load and portability.

Findability. Try to find the place `services.industries.automotive.text` is used and defined in our sources. With this PR you search for `services.industries.automotive.text` and you will see the places with the definition plus the ones using it. This helps tremendously when I want to update a specific key in the translation file. I can just search for `"services.industries.automotive.text`. With a nested structure you will painfully jump from level to level or search for partial patterns.  That's jsut wasting our precious time. Yes, there might be some IDE support to search for nested json keys but I don't want to rely on that fact at all. 

Cognitive load: I want to check for a few keys in the translation file. For every single key I have to walk the hierarchy while I could just go through a plain flat list as demonstrate with this PR. I'm much more efficient as my mind don't have to resolve the different hierarchies.

Portability: Nested json format ist not supported in most translation systems. So it's kind of a requirement to maintain a flat list.

---

I haven't had fixed opinion before when we introduced the translation files but over the past weeks my opinion got more clear every time I touched the files. That's why I'm happy to provide this PR and I hope m explanations make sense to you. For the future I won the discovery that I will never accept nested translations again from the beginning 😁

**Comment by hofmann-felix** [comment]
@georgiee Thank you for the explanation 🙏

**Pull request merged**
